version: 2

updates:
  # Python main
  - package-ecosystem: pip
    directory: "."
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 10
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Bats tests
  - package-ecosystem: npm
    directory: "/tests-cli"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 10
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
