language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
  homebrew:
    update: true

matrix:
  include:
    - { if: branch = master, os: linux, dist: "" }
    - { if: branch = master, os: linux, dist: bionic }
    - { if: branch = master, os: linux, dist: xenial }
    - { if: branch = master, os: linux, dist: trusty }
    - { if: branch = master, os: linux, dist: precise }

before_install:
  - uname -a
  - if [ "$(uname -s)" = 'Darwin' ]; then sw_vers; fi
  - python3 --version

install:
  - make bootstrap

script:
  - make test
  - make install DESTDIR="${HOME}"
