language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
      - upx
  homebrew:
    update: true
    packages:
      - upx

before_install:
  - uname -a
  - if [ "$(uname -s)" = 'Darwin' ]; then sw_vers; fi

install:
  - make bootstrap

script:
  - make lint build test
  - make install DESTDIR="${HOME}"
