language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
  homebrew:
    update: true

before_install:
  - uname -a
  - if [ "$(uname -s)" = 'Darwin' ]; then sw_vers; fi

install:
  - make bootstrap
  - make sysinfo

script:
  - make test
  - make install DESTDIR="${HOME}"
